apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: library-app
  namespace: argo-apps-conf
spec:
  project: apps-acc
  
  source:  
    repoURL: https://github.com/cpjboon/argocd.git
    targetRevision: HEAD
    path: apps/library-app/overlays/acc
  destination:
    server: https://kubernetes.default.svc
    namespace: library-app-acc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

